# Generated by Django 4.2.4 on 2023-08-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(blank=True, max_length=200, null=True)),
                ('full_name', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
