# Generated by Django 4.2.4 on 2023-08-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_name', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=150)),
                ('from_time', models.DateField(blank=True, null=True)),
                ('to_time', models.DateField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('position', models.CharField(blank=True, max_length=150, null=True)),
                ('from_time', models.DateField(blank=True, null=True)),
                ('to_time', models.DateField(blank=True, null=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
