# Generated by Django 4.2.4 on 2023-08-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_education_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='to_time',
            field=models.DateField(blank=True, default='Current', null=True),
        ),
    ]
