# Generated by Django 4.2.4 on 2023-08-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('profession', models.CharField(max_length=100)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv')),
            ],
        ),
    ]
